version: "3"
services:
  api:
    build: ./api
    container_name: api
    ports:
      - 8080:8080
    depends_on:
      - devdb
    links:
      - devdb
  
  devdb:
    image: mongo:latest
    container_name: devdb
    restart: always
    volumes:
      - devdb:/data/db
    ports:
      - 27017:27017

volumes:
  devdb: