server:
  port: 8080

spring:
  application:
    name: horizon-drive
#  data:
#    mongodb:
#      host: devdb
#      port: 27017
#      database: devdb

token:
  key: "UBuIpl5UE1TY9z5Wl59Hu4TskYLleNcs"
  expiration: "3600"
