server:
  port: 8080

spring:
  application:
    name: horizon-drive
  data:
    mongodb:
      host: devdb
      port: 27017
      database: devdb

token:
  key: "secret33333333333333secret33333333333333"
  expiration: "3600"
