FROM openjdk:11

ADD build/libs/horizon-drive-0.0.1-SNAPSHOT.jar horizon-drive-0.0.1-SNAPSHOT.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "horizon-drive-0.0.1-SNAPSHOT.jar"]

MAINTAINER Artur Jakubowski